### ISSUE TITLE
Why the results of AD-GCL are different from its original paper (请问没什么AD-GCL的结果不是原文的结果)

### ISSUE THREAD

**Issue by Wu-Junran** [lsh0520/RGCL#3] opened 2022-09-02 05:24 UTC
Meanwhile, why not adopt JOAO as baseline, as you employ the AD-GCL and AD-GCL made comparison with JOAO.（同时，为什么不和JOAO做比较，毕竟你引用了AD-GCL那么应该知道JOAO的存在的）

The results of JOAO and AD-GCL in unsupervised learning with non-linear SVM are attached below： (下面附上JOAO和AD-GCL的无监督原文（非线性SVM）结果)：

Data | NCI1 |PROTEINS |DD |MUTAG |COLLAB |RDT-B |RDT-M5K |IMDB-B
:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
JOAO | 78.07 | 74.55|77.32|87.35|69.50|85.29|55.74|70.21
JOAOv2| 78.36 | 74.07 | 77.40 | 87.67 | 69.33 | 86.42 | 56.03 | 70.83
AD-GCL-FIX |75.77|75.04|75.38|88.62|74.79|92.06|56.24|71.49
RGCL|78.14|75.03|78.86|87.66|70.92|90.34|56.38|71.85

**Comment by lsh0520** [comment] 2022-09-20 03:07
Thank you for your comments and sorry for the late reply. I'm having a very busy Sept.

1. As I mentioned in my paper, the resulrs of AD-GCL are reproduced on our platform (RTX 3090). I would appreciate it if you can double-check by downloading from their official codebase on github and running on your platform.
![image](https://user-images.githubusercontent.com/28565053/191156043-711678bd-beb4-46de-85e1-14f50931e14e.png)

2. I overlooked JOAO since it didn't appear in the main body of AD-GCL and I only focused on Table 8 in appendix.
![image](https://user-images.githubusercontent.com/28565053/191157034-d0f7696e-367a-45fe-8f12-feab0e4ace56.png)

But thank you for pointing out and JOAO should and will be included in my arxiv version (camera-ready version is already fixed), both transfer learning and unsupervised learning.

**Comment by Wu-Junran** [comment] 2022-09-20 03:46
Yes, if everyone reproduces the code and reports new results, everyone can have the higher results and SOTA position. 

Good luck for you.

**Closed** 2022-09-20 06:40 UTC
